name: openduck_latest
channels:
  - bioconda
  - omnia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - yank=0.25.2
  - pdbfixer=1.6
  - openforcefield==0.7.2
  - parmed=3.2.0
  - cudatoolkit=10.1.243
  - openmm=7.4.1=py37_cuda101_rc_1
