name: prepare
channels:
  - schrodinger
  - omnia 
  - conda-forge
  - rbetz
  - rdkit
dependencies:
  - python=2.7
  - yank
  - rdkit
  - vmd-python 
  - openbabel
  - pymol
  - openforcefield
  - pdbfixer
