name: openduck_latest
channels:
  - bioconda
  - omnia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - yank=0.25.2
  - pdbfixer=1.6
  - openforcefield=0.7.2
  - parmed=3.4.3
  - cudatoolkit=11.7.0
  - openmm=7.5
  - openmmforcefields=0.7.4
  - ambertools=22.0
  - seaborn
