name: duck
channels:
  - abradle
  - schrodinger
  - omnia
  - conda-forge
  - rdkit
  - openbabel
dependencies:
  - python=3.6
  - yank
  - rdkit
  - openbabel
  - pymol
  - pdbfixer
  - openforcefield=swang