name: openduck
channels:
  - bioconda
  - omnia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - yank
  - pdbfixer
  - openforcefield=0.7.2
  - parmed
  - cudatoolkit
  - openmm=7.5
  - openmmforcefields
  - ambertools
