name: openduck
channels:
  - bioconda
  - omnia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - yank
  - pdbfixer
  - openforcefield
  - parmed
  - cudatoolkit
  - openmm
  - openmmforcefields
  - ambertools
