name: duck
channels:
  - abradle
  - schrodinger
  - omnia
  - conda-forge
  - rdkit
dependencies:
  - python=3.6
  - yank
  - rdkit=2018.03.2
  - pymol
  - pdbfixer
  - openforcefield=swang
  - pip:
    - duck-xchem