{% set name = "duck" %}
{% set version = "0.1.3" %}

package:
  name: openduck
  version: {{ version }}

source:
  url: https://github.com/simonbray/{{ name }}/archive/refs/heads/galaxy-version.tar.gz
  sha256: 5ee0cae33c07a3c0277d7db5a0c7a7f2bcd65752a54c3910edb6fcc64623dfc2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - get_wqb = scripts.get_wqb:main
    - duck_chunk=scripts.duck_chunk:main
    - duck_prepare_sys=scripts.duck_prepare_sys:main
    - duck_prepare_sys_for_amber=scripts.duck_prepare_sys_for_amber:main
    - duck_smd_runs=scripts.duck_smd_runs:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - rdkit
    - cudatoolkit
    - networkx
    - yank=0.25.2
    - pdbfixer=1.7
    - openff-toolkit=0.9.0
    - parmed=3.4.3
    - cudatoolkit=11.7.0
    - openmm=7.5
    - openmmforcefields=0.9.0
    - ambertools=22.0
    - seaborn=0.12

test:
  commands:
    - duck_smd_runs -h
    - duck_prepare_sys -h
    - duck_prepare_sys_for_amber -h
    - duck_chunk -h
    - get_wqb -h

about:
  home: https://github.com/galaxycomputationalchemistry/duck
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Open source library for dynamic undocking (DUck)
